# -*- coding: utf-8 -*-
"""Assemble index.html: src/head.html + one <script> with the data (generated from tools/content.py), 点点岛's engine,
the letters, the writer, the app layer and the games. Zero dependencies in the page; this script only concatenates.
usage: python tools/build.py"""
import os, sys, json, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from content import W1, W2, W3, CVC, WORDS2, FW_SENTS, READ, BOOKS
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src')
SKIN = {'s': 'avengers', 'peppa': 'peppa', 'bluey': 'bluey', 'huluwa': 'huluwa', 'paw': 'paw', 'xiyou': 'xiyou', 'ultra': 'avengers', 'robot': 'avengers', 'pj': 'avengers'}
AMB = {'s': 'city', 'peppa': 'rain', 'bluey': 'crickets', 'huluwa': 'wind', 'paw': 'waves', 'xiyou': 'falls', 'ultra': 'city', 'robot': 'city', 'pj': 'crickets'}
EN_SAY = {c: c for c in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'}


def letter_line(L, word):
    return '%s, %s!' % (L.upper() if L.isupper() else L.upper(), word)


def data_js():
    order, isl, items, item = {'w1': [], 'w2': [], 'w3': []}, {}, [], {}
    for wid, lst in (('w1', W1), ('w2', W2), ('w3', W3)):
        for i, d in enumerate(lst):
            iid = d['id']; root = iid.rstrip('2').rstrip('12') if iid in ('s1', 's2') else iid.rstrip('2')
            base = d.get('base') or ((1 if i < 4 else 2) if wid == 'w1' else (2 if i < 3 else 3))
            order[wid].append(iid)
            isl[iid] = dict(id=iid, w=wid, i=i, name=d['name'], host=d['host'], crew=d['crew'], color=d['color'], color2=d['color2'], hi=d['hi'], base=base, fw=bool(d.get('fw')),
                            skin=SKIN.get(root, 'avengers'), amb=AMB.get(root, 'city'),
                            chars=[dict(c=c, line=line, obj=obj, en=en) for c, line, obj, en in d['chars']],
                            letters=[dict(l=l, word=word, obj=obj) for l, word, obj in d['letters']], games=[])
            for c, line, obj, en in d['chars']:
                it = dict(k=c, kind='zh', isl=iid, obj=obj, line=line, en=en or None, word=en, fw=bool(d.get('fw')))
                items.append(it); item[c] = it
            for l, word, obj in d['letters']:
                it = dict(k=l, kind='up' if l.isupper() else 'lo', isl=iid, obj=obj, line=letter_line(l, word), word=word, say=EN_SAY[l.upper()], en=None)
                items.append(it); item[l] = it
    # every capital has a name to say even before its island (a lower-case letter is said by its capital's name)
    for c in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ':
        if c not in item:
            item[c] = dict(k=c, kind='up', isl='', obj='', line=c, word='', say=c, en=None)
    info = {'w1': dict(name='晨光海', map='map_w1', gate='gate1', fest='fest1', finale='finale_w1'),
            'w2': dict(name='星光海', map='map_w2', gate='gate2', fest='fest2', finale='finale_w2'),
            'w3': dict(name='彩虹海', map='map_w3', gate='gate1', fest='fest2', finale='finale_w2', partial=True)}
    j = lambda o: json.dumps(o, ensure_ascii=False, separators=(',', ':'))
    out = ['/* ================================================================ DATA (generated by tools/build.py from tools/content.py) */',
           'const ORDER = ' + j(order) + ';', 'const WORLDS_INFO = ' + j(info) + ';', 'const ISL = ' + j(isl) + ';',
           'const ITEMS = ' + j(items) + ';', 'const ITEM = ' + j(item) + ';',
           'const CVC_WORDS = ' + j(CVC) + ';', 'const CVC_OBJ = ' + j({w: o for w, o in CVC}) + ';',
           'const WORDS2_LIST = ' + j(WORDS2) + ';', 'const WORDS2_OBJ = ' + j({a + b: o for a, b, o in WORDS2}) + ';',
           'const FW_SENTS = ' + j(FW_SENTS) + ';', 'const READ = ' + j(READ) + ';', 'const BOOKS = ' + j(BOOKS) + ';',
           'const META = ' + meta_js() + ';']
    return '\n'.join(out)


def meta_js():
    """the client's characters: their measured eyes (点点岛 META); the new ones: their size only (no blinking lids)"""
    src = open(r'D:\ClaudeCode\kidmath3\index.html', encoding='utf-8').read()
    m = re.search(r'const META = (\{.*?\});\n', src)
    meta = json.loads(m.group(1))
    cdir = os.path.join(ROOT, 'assets', 'chars')
    for f in os.listdir(cdir):
        k = f[:-4]
        if f.endswith('.png') and k not in meta:
            w, h = Image.open(os.path.join(cdir, f)).size
            meta[k] = [round(w * 496 / h), 496, []]
    return json.dumps(meta, separators=(',', ':'))


def main():
    head = open(os.path.join(SRC, 'head.html'), encoding='utf-8').read()
    parts = [data_js()] + [open(os.path.join(SRC, f), encoding='utf-8').read() for f in ('engine.js', 'letters.js', 'writer.js', 'app.js', 'games.js', 'games2.js', 'v2.js', 'v2b.js')]
    js = "'use strict';\n" + '\n'.join(parts) + '\nboot();\n'
    html = head + '<script>\n' + js + '</script>\n</body>\n</html>\n'
    open(os.path.join(ROOT, 'index.html'), 'w', encoding='utf-8', newline='\n').write(html)
    print('index.html', len(html.encode('utf-8')) // 1024, 'KB')


if __name__ == '__main__':
    main()
